### ISSUE TITLE
Preserve code blocks

### ISSUE THREAD

**Issue by macfreek** [sphinx-contrib/restbuilder#14]
In commits 24c637c by @bfabio and 55233c9 by @davidfritzsche improvements were made to preserve code blocks.

These improvements should be backported to this repository.

Requested actions:
* Add a test suite with examples, e.g. the examples in [docs/examples/examples.rst](https://github.com/sphinx-contrib/restbuilder/blob/55233c93060bf65e34b96d4daa9f8405b0fa2b7c/docs/examples/examples.rst).
* Add all changes by @bfabio
* Selectively add improvements by @davidfritzsche (since that commit also included some other minor changes)
* Always preserve code block flags, if possible (so there is no need for a `rst_preserve_code_black_flags` configuration parameter. If this is not possible, try to find a solution compatible with 55233c9.

**Comment by macfreek** [comment]
Pull request #21 fixes most (all?) these features:
* support for literal blocks
* support for `code-block` directive, including preserving language and `linenos` parameters
* support for `code` directive, including preserving language and `line-number` parameters
* Full support for Sphinx 2.0 and up. Partial support for Sphinx 1.4-1.8:
  * Sphinx 1.x does not support code directive without a language parameter.
  * Sphinx 1.x inserts line numbers manually. This is left as-is.
* The `literalinclude` directive is not yet tested.

**Comment by bfabio** [comment]
Thanks @macfreek !
