### ISSUE TITLE
An option to create fully qualified links

### ISSUE THREAD

**Issue by nedbat** [sphinx-contrib/restbuilder#19]
There is an important difference between this repo and davidfritzsche's: with his, all links are explicit.

This in my source .rst file:
```
see :ref:`whatsnew5x`.
```
becomes this with davidfritzsche's fork:
```
see `Major changes in 5.0 <whatsnew5x.rst#whatsnew5x>`_.
```
With this repo, it becomes:
```
see `Major changes in 5.0`_.
```
I'm using restbuilder to produce .rst files that pandoc can convert to markdown files.  These implicit references aren't resolvable by pandoc.   Is there an option I can use with this repo to get fully resolved links?

**Comment by macfreek** [comment]
Hi @nedbat, could you test the latest version?

Nearly all internal and external links are now properly supported. The only issue still left is the `:ref:` role that you use. `:ref:` is Sphinx-specific, and the output of restbuilder should not contain Sphinx-specific directives or roles. The issue that I can't find a good way to replicated the behaviour in "plain" reStructuredText, only something which is close. I put the technical details in #20.

**Comment by nedbat** [comment]
Thanks, the links are working now.  I'm not sure what you mean about an issue remaining with `:ref:`, those seem fine in my use.

There's an issue with list indentation which I will put into a new issue.

**Comment by macfreek** [comment]
> Thanks, the links are working now. I'm not sure what you mean about an issue remaining with `:ref:`, those seem fine in my use.

The issue is minor. In your above example:

    see :ref:`whatsnew5x`.

becomes:

    see `Major changes in 5.0 <whatsnew5x.rst#whatsnew5x>`_.

which would subsequently be rendered as:

    see <a class="reference external" href="whatsnew5x.rst#whatsnew5x">Major changes in 5.0</a>.

The `class="external"` is incorrect. It is an _internal_ reference. However, I can't think of a reStructuredText structure which produces internal links between two documents.

So for now, this is good enough. I will add some more tests and fix issues I encounter.

> There's an issue with list indentation which I will put into a new issue.

Please do. I'm there are plenty of bugs left, but adding issues will prioritise my efforts.

**Comment by macfreek** [comment]
More testing revealed that there was still a minor bug.

    see :ref:`whatsnew5x`.

would work if `whatsnew5x` was a target in a different file, but not if the target was in the same file. That is now fixed, so I have closed this issue.
