### ISSUE TITLE
Bulleted lists aren't indented optimally

### ISSUE THREAD

**Issue by nedbat** [sphinx-contrib/restbuilder#23]
Comparing this repo with davidfritzsche's: the indentation of bullet lists differ by a space.

With input like this:
```
Unreleased
----------

- ``coverage combine`` has a new option, ``--keep`` to keep the original data
  files after combining them.  The default is still to delete the files after
  they have been combined.  This was requested in `issue 1108`_ and implemented
  in `pull request 1110`_.  Thanks, Éric Larivière.

.. _issue 1108: https://github.com/nedbat/coveragepy/issues/1108
.. _pull request 1110: https://github.com/nedbat/coveragepy/pull/1110
```

davidfritzsche produces:
```
Unreleased
==========

* ``coverage combine`` has a new option, ``--keep`` to keep the original data
  files after combining them.  The default is still to delete the files after
  they have been combined.  This was requested in `issue 1108 <https://github.com/nedbat/coveragepy/issues/1108>`_ and implemented
  in `pull request 1110 <https://github.com/nedbat/coveragepy/pull/1110>`_.  Thanks, Éric Larivière.
```
This repo produces:
```
Unreleased
==========

* ``coverage combine`` has a new option, ``--keep`` to keep the
   original data files after combining them.  The default is still to
   delete the files after they have been combined.  This was requested
   in `issue 1108 <https://github.com/nedbat/coveragepy/issues/1108>`_
   and implemented in `pull request 1110
   <https://github.com/nedbat/coveragepy/pull/1110>`_.  Thanks, Éric
   Larivière.
```

I use pandoc to convert this to markdown, with a command like:
```
pandoc -frst -tmarkdown_strict --atx-headers --wrap=none /tmp/converted.rst
```

The good output gets converted to:
```
## Unreleased

-   `coverage combine` has a new option, `--keep` to keep the original data files after combining them. The default is still to delete the files after they have been combined. This was requested in [issue 1108](https://github.com/nedbat/coveragepy/issues/1108) and implemented in [pull request 1110](https://github.com/nedbat/coveragepy/pull/1110). Thanks, Éric Larivière.
```

Which renders accurately as Markdown:

## Unreleased

-   `coverage combine` has a new option, `--keep` to keep the original data files after combining them. The default is still to delete the files after they have been combined. This was requested in [issue 1108](https://github.com/nedbat/coveragepy/issues/1108) and implemented in [pull request 1110](https://github.com/nedbat/coveragepy/pull/1110). Thanks, Éric Larivière.

This repo's output gets converted to:
```
## Unreleased

-   `coverage combine` has a new option, `--keep` to keep the
    original data files after combining them. The default is still to delete the files after they have been combined. This was requested in [issue 1108](https://github.com/nedbat/coveragepy/issues/1108) and implemented in [pull request 1110](https://github.com/nedbat/coveragepy/pull/1110). Thanks, Éric Larivière.
```

which does not render correctly as Markdown:

## Unreleased

-   `coverage combine` has a new option, `--keep` to keep the
    original data files after combining them. The default is still to delete the files after they have been combined. This was requested in [issue 1108](https://github.com/nedbat/coveragepy/issues/1108) and implemented in [pull request 1110](https://github.com/nedbat/coveragepy/pull/1110). Thanks, Éric Larivière.

**Comment by macfreek** [comment]
Hi @nedbat,

Could you check if the recent version works?
I've rewritten the list-generation code, so I think all should be well (and the tests says so). The only thing not working is advanced list feature (e.g. numbered not starting with 1, or with alphabetic or roman numbers).

That said, I think a new version was overdue, so version 0.3 was just released. See https://github.com/sphinx-contrib/restbuilder/releases and https://pypi.org/project/sphinxcontrib-restbuilder/.

The last commit of this release is ba1ef7a. It is not a coincidence that a commit (ba1ef7a) with this commit message was the one that was tagged as the release. I appreciate your help, even in the form of issues. Thank you!

**Comment by nedbat** [comment]
Thanks, the released version works great!

Thanks for the shout-out in the CHANGES.rst, but you might want to say "Reported by", since I didn't fix it, but it looks like I did.

**Comment by macfreek** [comment]
> Thanks, the released version works great!

Glad to hear that. I'll close this ticket.

> Thanks for the shout-out in the CHANGES.rst, but you might want to say "Reported by", since I didn't fix it, but it looks like I did.

Unless you prefer to remain anonymous, I leave it as-is for now. It's not that many people will read it. And if anyone cares, you did submit a PR to the other repo; and for the nitty-gritty details there is also the CONTRIBUTORS.txt and commit log. I appreciate your help, and to me, that's all that the shoutout in the change log is about. Thanks.
